### ISSUE TITLE
TODO: Add 95 pixels (or equivalent) of spacing below the search app's About page text.

### ISSUE THREAD

**Issue by DrewNaylor** [DrewNaylor/Retiled#217]
This will make it easier to read by not having to go to the very bottom to see everything.

See Windows Phone design guidelines: https://learn.microsoft.com/en-us/archive/blogs/africaapps/uxui-guidelines-for-windows-phone-8

**Comment by tarunsamanta2k20** [comment]
I would like to work on this issue.

**Comment by DrewNaylor** [comment]
Ok, thank you. I think it should be possible to put an Item below the Label containing the about page's text within the Flickable, that way the empty area can still be scrolled (regular QML margins don't like scrolling). Here's the QML file if you want to get started: https://github.com/DrewNaylor/Retiled/blob/main/RetiledSearch/RetiledSearch/pages/About.qml

**Comment by DrewNaylor** [comment]
Sorry, I got tired of waiting so I did it myself in d0b69c6.
